const SET_FIELD_VALUE = 'simple-form/SET_FIELD_VALUE';
const VALIDATION_ERROR = 'simple-form/VALIDATION_ERROR';
const VALIDATION_SUCCESS = 'simple-form/VALIDATION_SUCCESS';
const CLEAR_FIELD = 'simple-form/CLEAR_FIELD';

export {
  SET_FIELD_VALUE,
  VALIDATION_SUCCESS,
  VALIDATION_ERROR,
  CLEAR_FIELD,
};
